-- begin EMAILSENDER_RECEIVER
alter table EMAILSENDER_RECEIVER add constraint FK_EMAILSENDER_RECEIVER_ON_LETTER foreign key (LETTER_ID) references EMAILSENDER_LETTER(ID)^
create index IDX_EMAILSENDER_RECEIVER_ON_LETTER on EMAILSENDER_RECEIVER (LETTER_ID)^
-- end EMAILSENDER_RECEIVER
