alter table EMAILSENDER_HISTORY add constraint FK_EMAILSENDER_HISTORY_ON_LETTER foreign key (LETTER_ID) references EMAILSENDER_LETTER(ID);
create index IDX_EMAILSENDER_HISTORY_ON_LETTER on EMAILSENDER_HISTORY (LETTER_ID);
